apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: xfteam1-admins
users:
- developer1
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: xfteam1-users
users:
- developer1
- developer2
