apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators
  namespace: argocd
spec:
  project: default

  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'

  source:
    path: cluster/base/operators
    repoURL: 'https://github.com/jwennerberg/argocd-openshift.git'
    targetRevision: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    validate: true
