apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: xfteam1
  namespace: argocd
spec:
  description: xfteam1
  destinations:
    - namespace: 'vote-dev'
      server: '*'
    - namespace: 'vote-test'
      server: '*'
    - namespace: 'vote-prod'
      server: '*'
  sourceRepos:
    - "*"

  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy

  roles:
  - name: Admin access
    description: Admin privileges to applications
    policies:
    - p, proj:xfteam1:admin, applications, *, xfteam1/*, allow
    - p, proj:xfteam1:admin, applications, *, xfteam1, allow
    groups:
    - xfteam1-admins

  - name: Sync access
    description: Sync privileges
    policies:
    - p, proj:xfteam1:read-only, applications, get, xfteam1/*, allow
    - p, proj:xfteam1:read-only, applications, sync, xfteam1/*, allow
    groups:
    - xfteam1-users
