apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
data:
  policy.default: ""
  policy.csv: |
    g, argocdadmins, role:admin
    #g, argocdusers, role:readonly

    p, role:org-user, clusters, get, *, allow
    p, role:org-user, repositories, get, *, allow

    p, role:xfteam1-admins, applications, *, xfteam1/*, allow
    p, role:xfteam1-admins, projects, get, xfteam1, allow
    p, role:xfteam1-admins, applications, *, xfteam1-deploy/*, allow
    p, role:xfteam1-admins, projects, get, xfteam1-deploy, allow

    p, role:xfteam1-users, applications, get, xfteam1/*, allow
    p, role:xfteam1-users, applications, sync, xfteam1/*, allow
    p, role:xfteam1-users, projects, get, xfteam1, allow

    g, xfteam1-admins, role:xfteam1-admins
    g, xfteam1-users, role:xfteam1-users
    g, xfteam1-users, role:org-user
