apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

patchesJson6902:
- path: patch-deploymentconfig.yaml
  target:
    group: apps.openshift.io
    version: v1
    kind: DeploymentConfig
    name: ui
