apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-deploy
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/vote-deploy
    repoURL: 'https://github.com/jwennerberg/argocd-openshift.git'
    targetRevision: dev
  project: xfteam1-deploy
